### ISSUE TITLE
LEGAL: INSERT, UPDATE, DELETE - Store Users IP address

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#102]
**Overview**

By the law (TODO: **reference?**) we are to store IP address when content is created, updated or deleted.

**TODO:**

- [ ] Update privacy policy on when and how long an IP address is stored. 
- [ ] Store IP address on content modification starting from places where violations are more common (have publicly visible impact):
   - [ ] Topic create/update/delete
   - [ ] Argument (comment) create/update/delete
   - [ ] User create/update/delete
   - [ ] Group create/update/delete
   - [ ] Events create/update/delete
   - [ ] Report create/update/delete
   - [ ] Moderation create/update/delete
   - [ ] Attachments create/update/delete

**Comment by anettlinno** [comment]
Triage 58. COS have to provide proof of all activities (IP addresses) if user asks. We already save the IP addresses in activity feed for all the actions that users do. Continue saving this data in the activity feed database is probably most reasonable. We have to store this data for **four years** and for that reason we have to set expiration date for IP addresses. 

- [ ] Check the list of IP addresses that we already store and update the list if something is missing.
- [ ] After this issue is solved, we need to change "How long we may keep personal data" in Privacy Policy to four years: https://citizenos.com/legal/privacy/

**Comment by ilmartyrk** [comment]
1) Replace req.ip with x-forwarded for values.
2) Check if the previous list of endpoints/actions is covered
3) Update privacy policy if necessary

**Comment by tiblu** [comment]
> 1. Replace req.ip with x-forwarded-for values.

No need to do that. To my knowledge if Express.JS `trust proxy` is set to true, which is the case for our application deployments, `req.ip` will be taken from the `X-Forwarded-For` headers. In conclusion, I think `req.ip` is as good as it gets.

ALSO, as per Herokus Support (https://github.com/citizenos/citizenos-api/issues/217), there is absolutely NO WAY to guarantee the IP to be valid - a malicious User can damper `X-Forwarded-For` and Cloudflare headers to provide whatever they choose.

**Comment by tiblu** [comment]
## TODO

- [ ] Verify that `req.ip` takes into account `X-Forwarded-For` header. Verify in production environment.
- [ ] Store IP address on content modification starting from places where violations are more common (have publicly visible impact):
   - [ ] Topic create/update/delete
   - [ ] Argument (comment) create/update/delete
   - [ ] User create/update/delete
   - [ ] Group create/update/delete
   - [ ] Events create/update/delete
   - [ ] Report create/update/delete
   - [ ] Moderation create/update/delete
   - [ ] Attachments create/update/delete
- [ ] Update privacy policy on when and how long an IP address is stored.

**Comment by tiblu** [comment]
### Why and how to match a Etherpad content line to a User IP in Citizen OS

#### Why?
As a platform host we are responsible for the content.
If there is illegal content, we are to react on that. 
When there is a law-enforcement request, platform host has to match content to a User, more specifically IP.

**TODO: References for these requirements**

#### How?

* When EP content is updated, we call Citizen OS API with the help of `ep_webhooks` plugin to notify syncing EP content with API database.
* API will sync the pad content AND store an Activity to `Activities` table.
* The Activity DOES NOT contain the content itself (`description`) as there is no point of duplicating data in Activity. It  ONLY contains info that `description` changed.
* The Activity contains `actor` object which contains the User id in the Citizen OS system and the client IP making the change.
* By the Citizen OS User id you can look up `authorId` from `Users` table which is the Etherpad `authorId`.
* By the EP `authorId` you can find the actual lines introduced by this Etherpad author & Citizen OS User.

**Comment by tiblu** [comment]
**What was done?**

- Checklist with info what has been done - https://github.com/citizenos/citizenos-api/issues/102#issuecomment-1020097185
    - Most notable that modifying Etherpad content now stores correct client IP to the Activities table which makes it possible to trace EP changes. Writeup on how to trace EP changes - https://github.com/citizenos/citizenos-api/issues/102#issuecomment-1022239999
    - Went through all other activities, verified that  correct IP is stored in the `actor` object.
    - User update and delete do not store Activites. Discussion in Slack on the 28th of January 2022.
- New issue on actually not to store IPs for longer than promised 3 months - https://github.com/citizenos/citizenos-api/issues/226. Created new as it would explode the scope of this task and is fair to prioritize this separately.
- New issue on actually cleaning up after deleting a User - https://github.com/citizenos/citizenos-api/issues/226. Created new as it would explode the scope of this task and is fair to prioritize this separately.
