### ISSUE TITLE
Move away from digidoc service to new MID REST API and create container on API side

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#144]
SK has started to move away from digidoc service and as of 2019 they are not offering it to new clients. This means that all new customers who will want their own instance of Citizen OS will not be able to use Mobiil-ID and ID-card signig services. 

ToDo:
- [x] Investigate the possibility of using DigiDocService alternative that supposedly has the same API interface - https://github.com/open-eid/SiGa/wiki
- [x] Create containers on API side
- [x] Add Mobile-ID signatures to containers
- [x] Add Id-card signatures to containers

**Comment by tiblu** [comment]
> 2019-09-12 10:33:39 EEST - Tavo ToomemägiAnswer to Customer:
> Tere, Mikk
>  
> Aitäh, et oma küsimustega pöördusite, vastasel juhul oleks võinud juhtuda valesti mõistmine.
>  
> Selgitan üle:
>  
> * DigiDocService kaob täielikult ja selle KOGU funktsionaalsus liigub Mobiil-ID REST API osakas?
>  
> Vastus: DigiDocService kaob täielikult. Mobiil-ID REST API oskab vahendada vaid autentimise ja allkirjastamise päringud. Ehk saab olema analoogne Smart-ID REST APIga, millel on identne skoop.
> SK lõpetab allkirjastamise teenuse pakkumise st konteinerite kokku panemine ja ID-kaardi allkirjastamine.
> Alternatiivsed valikud oleme koondanud siia artiklisse: https://www.sk.ee/uudised/digidocservice-asendatakse-uue-mobiil-id-rest-api-ga/
>  
> * DigiDocService-st kaob Mobiil-ID funktsionaalsus, sinna jäävad endiselt alles konteinerite kokku panemise ja ID-kaardi allkirjastamise osa.
>  
> Vastus: DigiDocService kaob täielikult.
>  
> * DigiDocService kaob täielikult, sealhulgas konteinerite kokku panemise funktsionaalsus. Kõik peavad hakkama ise konteinereid oma serverites kokku panema ja siis Mobiil-ID REST API/ Smart ID API vms API-ga konteineri räsi allkirjastama?
>  
> See väide on tõene, täpselt nii hakkab olema.
>  
> --
> Lugupidamisega
>  
> Tavo Toomemägi
> tehnilise toe spetsialist
> SK ID Solutions AS

I double checked with SK support the future of Digi Doc Service (DDS) and it's clear now that it will be shut down completely, thus all parties have to start assembling containers on their side and only signing will be performed via a SK service.

We have to make a push to provide a Node.JS library that could possibly assemble valid containers. I'm confident that the library interests more parties that just Citizen OS or Rahvaalgatus thus we SHOULD compile a list of interested parties and start a joint venture of creating a great OSS library.

**Comment by tiblu** [comment]
**TODO:** Ask SK if whole DigiDocService would be OSS so that people could have their own server?

**Comment by tiblu** [comment]
Sent an e-mail to support@sk.ee asking about:
* Open sourcing of the whole DigiDocService (DDS).
* Exact time frame of closing the DDS.

**Comment by tiblu** [comment]
> 2019-09-18 17:18:32 EEST - Martin VestAnswer to Customer:
> Tere Mikk
>  
> DigiDocService'i koodi me avalikustada ei soovi.
> Riik on arendanud SiGa nimelise allkirjastamsie teenuse, millele nad on väidetavalt teinud ka DigiDocService'iga identse API ja see on opensource'na kättesaadav ja võimalik enda juures püsti panna. Teenusena nad teadaolevalt pakuvad vaid avalikele eteenustele. Viide: https://github.com/open-eid/SiGa/wiki
>  
> DigiDocService osas anname septembri jooksul kuupäeva teada aga hetkel saame öelda, et teenus on kättesaadav vähemalt aasta peale seda kui ametliku teavituse teeme.
>  
> --
>  
> Parimate soovidega
>  
> Martin Vest
> Tehnilise toe spetsialist
> SK ID Solutions AS

Takeways:

* DigiDocService (DDS) will NOT be OSS.
* There is an OSS alternative with identical API already OSS - https://github.com/open-eid/SiGa/wiki

**Comment by tiblu** [comment]
@ilmartyrk Does it make sense to take a look at this at the same time? https://github.com/citizenos/citizenos-api/issues/40

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
