### ISSUE TITLE
Update Etherpad-lite to 1.8

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#154]
A new long waited release https://github.com/ether/etherpad-lite/releases/tag/1.8.0 to Etherpad has just been released. As we have had many issues with Etherpad in the past. And as it should be more secure and stable we should upgrade to new version ASAP.
**TODO**:
- [x] - Update locally
- [x] - Check if all plugins work or if some need some modifications
- [x] - Run tests in our API project to see if everything is OK
- [x] - Check manually if UI is working normally and as intended
- [x] - Check exported docx files in vote containers

**TESTING:**

Plugins:

- [x] ep_align
- [x] ep_auth_citizenos
    - [x] authenticated access
    - [x] non authenticated access - covered by API autotests
          * "Fail - Forbidden - User membership was revoked from Group"
          * "Success - User can read public Topic"
- [x] ep_authorship_toggle
- [x] ep_comments_page - **depends on ep_inline_toolbar, ep_page_view**
    * Could not reproduce https://github.com/citizenos/citizenos-fe/issues/396 any more. 
- [x] ep_embed_floating_toolbar
- [x] ep_font_color
- [x] ep_font_size
- [x] ep_foot_note
- [x] ep_headings2
- [x] ep_image_upload - **TODO:** AWS conf needed!
- [x] ep_inline_toolbar - **dependency of ep_comments_page, ep_inline_voting**
- [x] ep_inline_voting - **depends on ep_inline_toolbar.**
    * Missing icon, but that was before release - https://github.com/citizenos/citizenos-fe/issues/398
- [x] ep_page_view - **dependency of ep_comments_page**
- [x] ep_resize
- [x] ep_themes_ext
- [ ] ep_title_limit
    * Little bugged, but was before EP upgrade. bug creaated - https://github.com/citizenos/ep_title_limit/issues/1
- [x] ep_webhooks
- [x] ep_translations - **TODO:** Verify that files are downloaded to the machine and in browser check for `html10n.translations`.
- [x] ep_embedded_hyperlinks2 - was implemented in testing env, but never released to live due to amount of bugs. NOT releasing it, removing from testing also.

Other:

- [x] Vote result download (docx)

**Comment by loorm** [comment]
Triage 16. Prioritize highly, because the 1.8 version improves security in important aspects.

**Comment by tiblu** [comment]
Live. Conf V145, application V146.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
