### ISSUE TITLE
REFACTOR: API/DB - "GroupMember" to "GroupMemberUser"

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#198]
**What is the user story?**
As a developer I would like to see consistency between Group and Topic so it makes sense to refactor "GroupMember" model to be "GroupMemberUser" 

**What is the requested feature?**
For consistency between Group and Topic, refactor "GroupMember" model to be "GroupMemberUser".

**Additional information.**

Related to:

* https://github.com/citizenos/citizenos-fe/issues/348

**Comment by loorm** [comment]
Triage 36. Estimated dev time 8 hours. Needs good testing, to make sure, nothing blows up as a result of the refactor. Prioritizing.

**Comment by tiblu** [comment]
**TODO**

- [ ] API - Rename all code occurances.
- [ ] DB - Migration to rename tables and ENUM-s.
- [ ] Verify if there is any impact on Activities. There MAY be translation keys that are concated from the model name, which means the Activities need migration.

**Comment by tiblu** [comment]
**Release notes***

Order:
* FE release 1: Add new activity translation keys by copying over old and renaming the keys.
* API
* DB
* FE release 2: Remove old activity translation keys.

**Comment by tiblu** [comment]
**DONE**

Total time spent 7 hours.
