### ISSUE TITLE
TECHNICAL DEPT: Topic / Group invites - remove "auto-accept" invite API interfaces

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#203]
**What?**

As part of https://github.com/citizenos/citizenos-fe/issues/112 and https://github.com/citizenos/citizenos-fe/issues/348 User MUST accept invite in order to join a Topic / Group. This supersedes the solution where User was automatically added to the Topic / Group.

**TODO**

- [x] Remove all "auto-accept" related API interfaces and tests. **Careful tho!** Some of the `/members`  interfaces are still used and are valid, not all of them are to go. Verify usage against logs.
- [x] Verify if `GET /api/invite/view` is still used, REMOVE IF NOT. Used by adding topic to group
- [x] Verify Citizen OS Topic / Group invite flows still work.
- [x] Pump major version of Citizen OS API
- [x] Update API changelog to reflect the change.

**Related to:**

* https://github.com/citizenos/citizenos-fe/issues/112
* https://github.com/citizenos/citizenos-fe/issues/348

**Comment by loorm** [comment]
Triage 37. Estimated dev time 6 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
FIXED by https://github.com/citizenos/citizenos-api/commit/c98bf936873edbb3987c0ba34b552dacb23aefe7 This turned out to be a bigger task, as I decided to update all tests too as there were quite many related to removed code. Also this helped to make tests running to be more consistent.
