### ISSUE TITLE
TECH DEPT: Testing - quite a number of tests are skipped that seem important

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#212]
**What?**

```
grep -r "skip" test/api 
test/api/internal/topic.js:                    test.skip('Success', async function () {
test/api/internal/notification.js:                test.skip('Success', async function () {
test/api/topic.js:                    test.skip('Fail - Bad Request - delegation is not allowed for the Vote', async function () {
test/api/topic.js:                    test.skip('Fail - Bad Request - option id does not belong to the Vote', async function () {
test/api/topic.js:                            test.skip('Fail - 40030 - Personal ID already connected to another user account.', async function () {
test/api/topic.js:                            test.skip('Fail - 40031 - User account already connected to another PID.', async function () {
test/api/topic.js:                        suite.skip('Sign', function () {
test/api/topic.js:                        test.skip('Fail - 40023 - Mobile-ID user certificates are revoked or suspended for Estonian citizen', async function () {
test/api/topic.js:                        test.skip('Fail - 40023 - Mobile-ID user certificates are revoked or suspended for Lithuanian citizen', async function () {
test/api/topic.js:                        test.skip('Fail - 40023 - User certificate is not activated for Estonian citizen.', async function () {
test/api/topic.js:                        test.skip('Fail - 40023 - Mobile-ID is not activated for Lithuanian citizen', async function () {
test/api/topic.js:                        test.skip('Fail - 40024 - User certificate is suspended', async function () {
test/api/topic.js:                        test.skip('Fail - 40025 - User certificate is expired', async function () {
test/api/topic.js:                test.skip('Success - public Topic', async function () {
test/api/topic.js:                test.skip('Fail - 403 - Forbidden - cannot comment on Topic you\'re not a member of or the Topic is not public', async function () {
test/api/topic.js:            test.skip('Get signed download url', async function () {
test/api/auth.js:                test.skip('Fail - 40024 - User certificate is suspended', async function () {
test/api/auth.js:                test.skip('Fail - 40025 - User certificate is expired', async function () {
test/api/auth.js:        test.skip('Success - signup sets redirectSuccess and verify should redirect to it', async function () {
test/api/auth.js:            test.skip('Success - 302 - User is NOT logged in AND has agreed before -> /login -> redirect_uri', async function () {
test/api/auth.js:            test.skip('Success - 302 - User is NOT logged in AND has not agreed before -> /login -> /consent -> redirect_uri', async function () {
test/api/auth.js:            test.skip('Success - 302 - User is NOT registered -> /register -> /verify -> /consent -> redirect_uri', async function () {
test/api/group.js:                    test.skip('Success', function () {
```

**TODO**

- [x] Go through all the skipped tests and see if:
    - [x] The test is neededed?
    - [x] Why is it skipped?
    - [x] Can we fix the test?
    - [x] Fix the tests.

**Comment by KatiVellak** [comment]
No legal impact.

**Comment by anettlinno** [comment]
Triage 49. Needs review to decide if we have capacity to do the test. Est. review time 2 days.

**Comment by ilmartyrk** [comment]
test/api/auth.js:        	 'Success - signup sets redirectSuccess and verify should redirect to it' -> Success is already tested as a part of 'Login' suite.
test/api/auth.js:            'Fail - 40024 - User certificate is suspended' -> REMOVED as API returns NOT_MID_CLIENT
test/api/auth.js:            'Fail - 40025 - User certificate is expired' -> REMOVED API returns NOT_MID_CLIENT
test/api/topic.js:           'Fail - Bad Request - send to Parliament - invalid contact info. Missing or invalid name, email or phone' -> REMOVED NO FUNCTIONALITY
test/api/topic.js:           'Fail - Bad Request - send to Parliament - not enough votes to send to Parliament' -> REMOVED NO FUNCTIONALITY
test/api/topic.js:           'Success - send to Parliament' -> REMOVED NO FUNCTIONALITY
test/api/topic.js:           'Fail - 40024 - User certificate is suspended' -> REMOVED API returns NOT_MID_CLIENT
test/api/topic.js:           'Fail - 40025 - User certificate is expired' -> REMOVED API returns NOT_MID_CLIENT
test/api/topic.js:           'Fail - 40030 - Personal ID already connected to another user account.' -> REMOVED multiple users with same PID are allowed
test/api/topic.js:           'Get signed download url' -> REMOVED

test/api/topic.js:           'Fail - 40023 - Mobile-ID user certificates are revoked or suspended for Estonian citizen' -> FIXED
test/api/topic.js:           'Fail - 40023 - Mobile-ID user certificates are revoked or suspended for Lithuanian citizen' -> FIXED
test/api/topic.js:           'Fail - 40023 - User certificate is not activated for Estonian citizen.' -> FIXED
test/api/topic.js:           'Fail - 40023 - Mobile-ID is not activated for Lithuanian citizen' -> FIXED
test/api/topic.js:           'Fail - Bad Request - delegation is not allowed for the Vote' -> FIXED, added test
test/api/topic.js:           'Fail - Bad Request - option id does not belong to the Vote' -> FIXED, added test
test/api/topic.js:           'Fail - 40031 - User account already connected to another PID.' -> FIXED, added test
test/api/auth.js:            'Success - 302 - User is NOT logged in AND has agreed before -> /login -> redirect_uri' -> FIXED, added test
test/api/auth.js:            'Success - 302 - User is NOT logged in AND has not agreed before -> /login -> /consent -> redirect_uri' -> FIXED, added test

test/api/auth.js: 'Success - 302 - User is NOT registered -> /register -> /verify -> /consent -> redirect_uri' -> Not sure how to properly solve
test/api/topic.js: 'ID-Card Sign' -> Needs certificate and private key, not sure how to get one for ID-card testing
