### ISSUE TITLE
[SECURITY] Login vulnerable to brute-force attacks

### ISSUE THREAD

**Issue by EgidioRomano** [citizenos/citizenos-api#217]
**What is the problem?**
The issue exists because of a missing mechanism to prevent multiple authentication requests in a short time frame. This could be exploited by unauthenticated attackers to discover users' passwords and take over accounts. Please find attached a Proof of Concept script ([brute_force.zip](https://github.com/citizenos/citizenos-api/files/7569772/brute_force.zip)) to reproduce the issue - it's a PHP script supposed to be used from the command line (CLI). You should see an output like the following:

```
$ php brute_force.php 
[-] Brute-forcing password for user 'n0b0d13s@gmail.com'...
[1] Trying with '123'
[2] Trying with '1234'
[3] Trying with '12345'
[4] Trying with '123456'
[5] Trying with 'aaa'
[6] Trying with 'abc'
[7] Trying with 'admin'
[8] Trying with 'administrator'
[9] Trying with 'athena'
[10] Trying with 'atmosphere'
...
[96] Trying with 'help'
[97] Trying with 'herbert'
[98] Trying with 'hiawatha'
[99] Trying with 'hibernia'
[100] Trying with 'hidden'
[101] Trying with 'holly'
[102] Trying with 'hom3w0rK'
[-] It looks like we found the password! :)
```

**Possible solution.**
It is suggested to implement an efficient account lockout mechanism within the login API endpoint. Alternatively, you could also use CAPTCHAs to prevent automated brute-force attacks. For more info: https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks

**Comment by ilmartyrk** [comment]
Hi and thank you @EgidioRomano for all your effort and information. We went through all your information and are thinking of different solutions on how to fix. Currently we are thinking that easiest and fastest solution for us is to add rate-limiting and slow-down. From our point-of-view this should be enough to quickly provide solution for this issue. After that we can discuss further solutions on how to overcome this issue.

**Comment by EgidioRomano** [comment]
Hi @ilmartyrk!

As a fix to quickly provide a solution for this issue, rate-limiting should be fine. But I think this isn't enough: like I wrote in my email, this could be bypassed by [rotating IP addresses](https://rhinosecuritylabs.com/aws/bypassing-ip-based-blocking-aws/), as such I would suggest implementing further proper solutions.

**Comment by tiblu** [comment]
> Hi @ilmartyrk!
> 
> As a fix to quickly provide a solution for this issue, rate-limiting should be fine. But I think this isn't enough: like I wrote in my email, this could be bypassed by [rotating IP addresses](https://rhinosecuritylabs.com/aws/bypassing-ip-based-blocking-aws/), as such I would suggest implementing further proper solutions.

Thanks for the info again!

Other non-IP based methods that come to mind:

* Input based method - we look at the data input (payload) and identify values that we rate limit and/or slow-down. For example: for login, we do limiting based on "email" in the payload. That is - you can only try to log in with "john.smit@gmail.com" email 10 times in 15 minutes.

Any other ideas that come to mind @EgidioRomano @ilmartyrk ?

**Comment by EgidioRomano** [comment]
@tiblu you're correct: IP based restrictions make attacks more "complicated", but not impossible! I think the best solution is "Locking Accounts" - see [this OWASP page](https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks).

For instance, you could use two new fields in the users database table: one should be a timestamp, indicating the last time a login attempt has been made for a specific user, and the other should be a numeric value, let's say "numAttempt", which is incremented if the last login attempt has been made within e.g. an hour from the last time - otherwise "numAttempt" should be set to 0. When "numAttempt" has reached e.g. 10 (failed attempts), you should lock out that specific user account, which could be unblocked manually by a system administrator or by the user itself, sending them an email with a link to unblock the account. Does that make sense?

**Comment by anettlinno** [comment]
Triage 52. Sending to development.

**Comment by tiblu** [comment]
**Action plan**

- [ ] Ask Heroku how is an app supposed to get REAL user IP in an app code? The problem is complex as app can be accessed directly over Heroku DNS (cannot trust `CF-Connecting-IP`) and via CloudFlare. Also, both of them allow dampering of `X-Forwarded-For` header possibly because use behind proxies.
- [ ] Implement input velocity based rate-limit / slow-down. Probably will follow the configuration scheme of the IP based projects.
- [ ] Add monitoring (logging on WARN level) for velocity / suspicious activity events.

**Comment by tiblu** [comment]
## Getting clients real IP in a Node.JS application (Heroku, Heroku + CloudFlare)

We're trying to figure out a way to get real client IP in our Node.JS application deployed to Heroku and having CloudFlare DNS and proxy enabled. 
We need the real client IP to implement IP based checks as a layer of security.

Example app endpoint: https://api.citizenos.com/api/stats (citizenos-citizenos-api-prod)

**Problem in short:**

 `X-Forwarded-For` request header cannot be trusted as `X-Forwarded-For` header can be tampered by the client - both Heroku and CloudFlare trust the incoming `X-Forwarded-For` and append it's content to the begining of their own `X-Forwarded-For` content. When an app uses the standard behavior of reading the first IP in the `X-Forwarded-For` request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For), it can be dampered by the client sending it's own `X-Forwarded-For` header.

### Proof case 1: Through CloudFlare proxy (CloudFlare - Heroku GW - App)

* Created an Node.JS route `/api/stats` which logs `req.headers` (`logger.info(`REQIP: ${req.ip}`, JSON.stringify(req.headers, null, 2));` - https://github.com/citizenos/citizenos-api/blob/71e163f469d1111f26e493e4ad3e43d780225823/routes/api/stats.js#L15.
* Used CURL request to call the endpoint through CloudFlare with my own determined `X-Forwarded-For` headers.

```
➜  ~ curl -i -k -H 'x-forwarded-for: 8.8.8.8' 'https://api.citizenos.com/api/stats?curl'

2021-11-29T16:02:53.385244+00:00 app[web.2]: [2021-11-29T16:02:53.385] [INFO] production - REQIP: 8.8.8.8 {
2021-11-29T16:02:53.385245+00:00 app[web.2]: "host": "api.citizenos.com",
2021-11-29T16:02:53.385255+00:00 app[web.2]: "x-forwarded-for": "8.8.8.8,82.131.73.205, 162.158.203.67",
2021-11-29T16:02:53.385257+00:00 app[web.2]: "cf-connecting-ip": "82.131.73.205",
...
```

**Result:**

* My custom `X-Forwarded-For` request header content is appended to the beginning of the list that the app actually sees. 
* There is no way to figure out the actual connecting client IP because it can be anywhere in the `X-Forwarded-For` IP list IF the `X-Forwarded-For` header is sent by the client (dampered)
* CloudFlare sends `cf-connecting-ip` which IS the correct client IP, BUT that cannot be used as Heroku APP can be accessed driectly over Heroku DNS (https://citizenos-citizenos-api-prod.herokuapp.com/api/stats) where this header does not exist and can be dampered.

### Proof case 2: Directly call Heroku with Heroku DNS (Heroku  GW - App)

* Created an Node.JS route `/api/stats` which logs `req.headers` (`logger.info(`REQIP: ${req.ip}`, JSON.stringify(req.headers, null, 2));` - https://github.com/citizenos/citizenos-api/blob/71e163f469d1111f26e493e4ad3e43d780225823/routes/api/stats.js#L15.
* Used CURL request to call the endpoint directly over Heroku DNS with my own determined `X-Forwarded-For` headers.

```
curl -i -k -H 'x-forwarded-for: 8.8.8.8' 'https://citizenos-citizenos-api-prod.herokuapp.com/api/stats?curl_no_cf'

2021-11-29T16:07:23.348281+00:00 app[web.1]: [2021-11-29T16:07:23.348] [INFO] production - REQIP: 8.8.8.8 {
2021-11-29T16:07:23.348281+00:00 app[web.1]: "host": "citizenos-citizenos-api-prod.herokuapp.com",
2021-11-29T16:07:23.348282+00:00 app[web.1]: "x-forwarded-for": "8.8.8.8, 82.131.73.205",
```

**Result:**

* My custom `X-Forwarded-For` request header content is appended to the beginning of the list that the app actually sees. 
* The actual client IP is the LAST IP in the list while the Wikipedia (https://en.wikipedia.org/wiki/X-Forwarded-For#Format) and MDN (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) say that the actual connecting client IP should be the first one in the list and most apps, including Express JS, expect that to be true. Right now for Express.JS the "real ip" is actually the dampered one.


### Ideas / possible solutions?

Some ideas and proposals to get the actual client IP. Throwing all of them out, not sure which are actually doable.

1. Somehow make it impossible to access our Heroku app over Heroku DNS directly (that is not on *.herokuapp.com), only through CloudFlare proxies. Then we can trust the `cf-connecting-ip`. Possible?
2. Force Heroku GW to overwrite incoming `X-Forwarded-For` header so that it cannot be dampered. It's like "trust proxy" flag in Express.JS based on which either incoming client IP is regarded as the actual client IP (false) OR the first IP in the `X-Forwarded-For` header (true)? the Possible?
3. Force CloudFlare to overwrite incoming `X-Forwarded-For` header so that it cannot be dampered. Possible?
4. Heroku should respect the standard (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) and have actually connecting client IP first in the list of `X-Forwarded-For` header which would make standard libraries work and there would be no separate code/configuration based on if the app is deployed on Heroku or not. The IP is always right.
5. Heroku may want to implement GW functionality where the actual connecting IP is put in a separate request header like `X-Real-IP` (Used by Oracle, Nginx real ip module...). CloudFlare has it as `cf-connecting-ip`.
6. ...?


### Conclusion

I feel like getting the real ip of a client is important in implementing IP based layer of security, but as it stands I find it impossible to get the real client IP that I can trust in CloudFlare+Heroku combo.
Also, non-standard implementations like the real client IP not being in the beginning of the `X-Forwarded-For` header make an app deployment too dependent on the environment, in this case none of the IP based security measures actually work when an Express app is deployed to Heroku.

**Comment by tiblu** [comment]
> @tiblu you're correct: IP based restrictions make attacks more "complicated", but not impossible! I think the best solution is "Locking Accounts", the "Input based method" you was talking about - see also [this OWASP page](https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks) for more information.
> 
> For instance, you could use two new fields in the users database table: one should be a timestamp, indicating the last time a login attempt has been made for a specific user, and the other should be a numeric value, let's say "numAttempt", which is incremented if the last login attempt has been made within e.g. an hour from the last time - otherwise "numAttempt" should be set to 0. When "numAttempt" has reached e.g. 10 (failed attempts), you should lock out that specific user account, which could be unblocked manually by a system administrator or by the user itself, sending them an email with a link to unblock the account. Does that make sense?

@EgidioRomano Yes, as confirmed on the OWASP page, there is no perfect solution. There are layers of different solutions that make hacking more expensive (time + money).

So we have the options - locking accounts and input based method on the table.

### Locking accounts

Pros:

* Easy to implement.
*  ... ?

**Cons:**

* May be used maliciously - that is, lets say there is an ongoing vote and a malicious party MAY try to lock out as many accounts as possible to manipulate vote results by stopping people from voting.
* ... ?

### Input based method

Pros:

* Relatively easy to implement.
* ... ?


Cons:

* Must be very careful with the rules so that legitimate requests don't trigger.
* May be used maliciously - that is, lets say there is an ongoing vote and a malicious party MAY try to lock out as many accounts as possible (by triggering limit on login email) to manipulate vote results by stopping people from voting.
* ... ?

**Comment by tiblu** [comment]
### Input based velocity

**Idea:** Look at the input - parameters and/or body values - and set velocity limits based on that.
**Example:** The login (`POST /api/auth/login`) which takes payload of `{"username": "myuser@pleep.com", "password": "superSecret"}`. We could make a middleware that takes dot notation of the parameter(s) to check and other configuration like so - `inputVelocity(['req.body.username'], '24h', 20)` - this tells that this route can have same `username` value in the body used 20 times in 24h window.

Implementation notes:

* I think it's best to use https://github.com/animir/node-rate-limiter-flexible internally as it solves the storage and counter and configuration issue for us.

**Comment by EgidioRomano** [comment]
Hi @tiblu, I like the idea! After a first glance at the code, I THINK it should solve the problem... Unless there's a way for the attacker to tamper the key by e.g. manipulating the value of `req.method` or `req.route.path` for every request, not sure this is possible, but you never know.

**Comment by tiblu** [comment]
> Hi @tiblu, I like the idea! After a first glance at the code, I THINK it should solve the problem... Unless there's a way for the attacker to tamper the key by e.g. manipulating the value of `req.method` or `req.route.path` for every request, not sure this is possible, but you never know.

@EgidioRomano thanks for having a look!

I chose `req.route.path` as I THINK it cannot be modified, this is the path in route definition and does not contain any changing parameters. Not taken from the HTTP request itself.
I chose `req.method` as IF you modify this, wrong route is called or the route does not resolve. AND, it was more of a pain to read it from `req.route....`.

That said, I will do more verification on this once I have some kind of satisfiable state of code. It needs more work.

What we do have to make sure is that we do not blow the memory/storage with this kinds of checks. If you add multiple parameters the key gets long and the number of combinations MAY go very high. So one kind of attack would be just to generate new keys with random input to blow drop the server. This is where I hope to apply some restrictions based on IP once we hear back from Heroku on the real-ip issue.

Thanks again for all your support!

**Comment by tiblu** [comment]
> @ilmartyrk @EgidioRomano sent this e-mail to Heroku support. Feel free to comment on this!
> 
> ## Getting clients real IP in a Node.JS application (Heroku, Heroku + CloudFlare)
> We're trying to figure out a way to get real client IP in our Node.JS application deployed to Heroku and having CloudFlare DNS and proxy enabled. We need the real client IP to implement IP based checks as a layer of security.
> 
> Example app endpoint: https://api.citizenos.com/api/stats (citizenos-citizenos-api-prod)
> 
> **Problem in short:**
> 
> `X-Forwarded-For` request header cannot be trusted as `X-Forwarded-For` header can be tampered by the client - both Heroku and CloudFlare trust the incoming `X-Forwarded-For` and append it's content to the begining of their own `X-Forwarded-For` content. When an app uses the standard behavior of reading the first IP in the `X-Forwarded-For` request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For), it can be dampered by the client sending it's own `X-Forwarded-For` header.
> 
> ### Proof case 1: Through CloudFlare proxy (CloudFlare - Heroku GW - App)
> * Created an Node.JS route `/api/stats` which logs `req.headers` (`logger.info(`REQIP: ${req.ip}`, JSON.stringify(req.headers, null, 2));` - https://github.com/citizenos/citizenos-api/blob/71e163f469d1111f26e493e4ad3e43d780225823/routes/api/stats.js#L15
>   .
> * Used CURL request to call the endpoint through CloudFlare with my own determined `X-Forwarded-For` headers.
> 
> ```
> ➜  ~ curl -i -k -H 'x-forwarded-for: 8.8.8.8' 'https://api.citizenos.com/api/stats?curl'
> 
> 2021-11-29T16:02:53.385244+00:00 app[web.2]: [2021-11-29T16:02:53.385] [INFO] production - REQIP: 8.8.8.8 {
> 2021-11-29T16:02:53.385245+00:00 app[web.2]: "host": "api.citizenos.com",
> 2021-11-29T16:02:53.385255+00:00 app[web.2]: "x-forwarded-for": "8.8.8.8,82.131.73.205, 162.158.203.67",
> 2021-11-29T16:02:53.385257+00:00 app[web.2]: "cf-connecting-ip": "82.131.73.205",
> ...
> ```
> 
> **Result:**
> 
> * My custom `X-Forwarded-For` request header content is appended to the beginning of the list that the app actually sees.
> * There is no way to figure out the actual connecting client IP because it can be anywhere in the `X-Forwarded-For` IP list IF the `X-Forwarded-For` header is sent by the client (dampered)
> * CloudFlare sends `cf-connecting-ip` which IS the correct client IP, BUT that cannot be used as Heroku APP can be accessed driectly over Heroku DNS (https://citizenos-citizenos-api-prod.herokuapp.com/api/stats) where this header does not exist and can be dampered.
> 
> ### Proof case 2: Directly call Heroku with Heroku DNS (Heroku GW - App)
> * Created an Node.JS route `/api/stats` which logs `req.headers` (`logger.info(`REQIP: ${req.ip}`, JSON.stringify(req.headers, null, 2));` - https://github.com/citizenos/citizenos-api/blob/71e163f469d1111f26e493e4ad3e43d780225823/routes/api/stats.js#L15
>   .
> * Used CURL request to call the endpoint directly over Heroku DNS with my own determined `X-Forwarded-For` headers.
> 
> ```
> curl -i -k -H 'x-forwarded-for: 8.8.8.8' 'https://citizenos-citizenos-api-prod.herokuapp.com/api/stats?curl_no_cf'
> 
> 2021-11-29T16:07:23.348281+00:00 app[web.1]: [2021-11-29T16:07:23.348] [INFO] production - REQIP: 8.8.8.8 {
> 2021-11-29T16:07:23.348281+00:00 app[web.1]: "host": "citizenos-citizenos-api-prod.herokuapp.com",
> 2021-11-29T16:07:23.348282+00:00 app[web.1]: "x-forwarded-for": "8.8.8.8, 82.131.73.205",
> ```
> 
> **Result:**
> 
> * My custom `X-Forwarded-For` request header content is appended to the beginning of the list that the app actually sees.
> * The actual client IP is the LAST IP in the list while the Wikipedia (https://en.wikipedia.org/wiki/X-Forwarded-For#Format) and MDN (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) say that the actual connecting client IP should be the first one in the list and most apps, including Express JS, expect that to be true. Right now for Express.JS the "real ip" is actually the dampered one.
> 
> ### Ideas / possible solutions?
> Some ideas and proposals to get the actual client IP. Throwing all of them out, not sure which are actually doable.
> 
> 1. Somehow make it impossible to access our Heroku app over Heroku DNS directly (that is not on *.herokuapp.com), only through CloudFlare proxies. Then we can trust the `cf-connecting-ip`. Possible?
> 2. Force Heroku GW to overwrite incoming `X-Forwarded-For` header so that it cannot be dampered. It's like "trust proxy" flag in Express.JS based on which either incoming client IP is regarded as the actual client IP (false) OR the first IP in the `X-Forwarded-For` header (true)? the Possible?
> 3. Force CloudFlare to overwrite incoming `X-Forwarded-For` header so that it cannot be dampered. Possible?
> 4. Heroku should respect the standard (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) and have actually connecting client IP first in the list of `X-Forwarded-For` header which would make standard libraries work and there would be no separate code/configuration based on if the app is deployed on Heroku or not. The IP is always right.
> 5. Heroku may want to implement GW functionality where the actual connecting IP is put in a separate request header like `X-Real-IP` (Used by Oracle, Nginx real ip module...). CloudFlare has it as `cf-connecting-ip`.
> 6. ...?
> 
> ### Conclusion
> I feel like getting the real ip of a client is important in implementing IP based layer of security, but as it stands I find it impossible to get the real client IP that I can trust in CloudFlare+Heroku combo. Also, non-standard implementations like the real client IP not being in the beginning of the `X-Forwarded-For` header make an app deployment too dependent on the environment, in this case none of the IP based security measures actually work when an Express app is deployed to Heroku.

**Herokus response:**

```
Hello Mikk,

Thanks for reaching out.
Let me start by mentioning that the X-Forwarded-For, X-Forwarded-By, X-Forwarded-Proto, and X-Forwarded-Host headers are not trusted for security reasons -- see https://devcenter.heroku.com/articles/http-routing#heroku-headers
Because it is not possible to know the order in which The X-Forwarded-For header already existing fields were added (as per Forwarded HTTP Extension). -- see https://datatracker.ietf.org/doc/html/rfc7239.html#section-7.4

if, for example, both
X-Forwarded-For and X-Forwarded-By exist. In such cases, it may not
be possible to do a conversion, since it is not possible to know in
which order the already existing fields were added. Also, note that
removing the X-Forwarded-For header field may cause issues for
parties that have not yet implemented support for this new header
field.
So trusting the "rightmost IP address" is not something we could assume. And would result in more incorrect fwd than correct.

To illustrate, let's say a user sends the following request from a machine IP of 8.8.8.8:

curl -H "X-Forwarded-For: 2.2.2.2,3.3.3.3,4.4.4.4" http://app_name.herokuapp.com
X-Forwarded-For would be 2.2.2.2,3.3.3.3,4.4.4.4, 8.8.8.8 and if we made an assumption that we trust the right-most IP address then fwd should be 8.8.8.8 right?
Now Imagine that this request was made behind a proxy IP of 9.9.9.9.
Then, X-Forwarded-For would be 2.2.2.2,3.3.3.3,4.4.4.4, 8.8.8.8, 9.9.9.9 and if we made an assumption that we trust the right-most IP address then fwd should be 9.9.9.9 which is not correct.
So, from Heroku standpoint. It is impossible to say which is the client IP.

Now think of the ratio of users that are behind a proxy (university, company, etc..) compared to users who are trying to spoof their IP.

Since most people won't be bothering to spoof their IP and from a practical standpoint (it's more likely that they are behind a proxy than they would be spoofing their IP), The client IP should in most cases be the left-most IP in the IP chain.

This is why Heroku chooses to use the left-most IP (to get the most correct results) while flagging X-Forwarded-For as not trusted.

I hope this explains it. Please let me know if you have further questions.

Regards,
Aly
```

**Comment by tiblu** [comment]
And my response to Heroku:

```
Hi Aly,

thanks for a thorugh explanation.

The original issue - Getting clients real IP in a Node.JS application (Heroku, Heroku + CloudFlare)
What are your ideas of actually getting a connecting client ip for the cases "mostly correct" is not enough and dampering is an issue?
I threw some ideas/questions out in the original post, but they must have gone under the radar:

Somehow make it impossible to access our Heroku app over Heroku DNS directly (that is not on *.herokuapp.com), only through CloudFlare proxies. Then we can trust the cf-connecting-ip. Possible?
Force Heroku GW to overwrite incoming X-Forwarded-For header so that it cannot be dampered. It's like "trust proxy" flag in Express.JS based on which either incoming client IP is regarded as the actual client IP (false) OR the first IP in the X-Forwarded-For header (true)? Possible?
Force CloudFlare to overwrite incoming X-Forwarded-For header so that it cannot be dampered. Possible?
~~Heroku should respect the standard (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) and have actually connecting client IP first in the list of X-Forwarded-For header which would make standard libraries work and there would be no separate code/configuration based on if the app is deployed on Heroku or not. The IP is always right. ~~This is the above discussion, wether there is a good way or not..
Heroku may want to implement GW functionality where the actual connecting IP is put in a separate request header like X-Real-IP (Used by Oracle, Nginx real ip module...). CloudFlare has it as cf-connecting-ip. Possible? Thoughts?
Discussion on your response
Now think of the ratio of users that are behind a proxy (university, company, etc..) compared to users who are trying to spoof their IP.

Can you please elaborate what kind of proxies are you talking about? What would the example request lifecycle? I seem to lack some knowledge here.

Talking about your example, curl -H "X-Forwarded-For: 2.2.2.2,3.3.3.3,4.4.4.4" http://app_name.herokuapp.com, I wish the client IP was the first in the X-Forwarded-For, but this is not how it works in Heroku right now.
My example:

curl -i -k -H 'x-forwarded-for: 8.8.8.8' 'https://citizenos-citizenos-api-prod.herokuapp.com/api/stats?curl_no_cf'

2021-11-29T16:07:23.348281+00:00 app[web.1]: [2021-11-29T16:07:23.348] [INFO] production - REQIP: 8.8.8.8 {
2021-11-29T16:07:23.348281+00:00 app[web.1]: "host": "citizenos-citizenos-api-prod.herokuapp.com",
2021-11-29T16:07:23.348282+00:00 app[web.1]: "x-forwarded-for": "8.8.8.8, 82.131.73.205",
How it works now: it does NEW X-Forwared-For = X-Forwarded-For + connecting client IP. Thats a fact, that I have proven above.
It should do: NEW X-Forwared-For = connecting client IP + X-Forwarded-For (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For). Even if it is a proxy server connecting, then it should be proxyIP + X-Forwarded-For That is, IF MDN is correct.
```

**Comment by tiblu** [comment]
### Relased - 09.12.2021

* Created a new Express middleware that enables configuration of limits based on user input:
    * Src: https://github.com/citizenos/citizenos-api/blob/9bfa481344e03cba533d66305b81210b0d638b42/libs/middleware/expressRateLimitInput.js
    * Example usage: https://github.com/citizenos/citizenos-api/blob/9bfa481344e03cba533d66305b81210b0d638b42/routes/api/auth.js#L282
* Rate limits apply ONLY to username/password login.
* When any of the limits - IP based rate or slow-down, input based - hits, API returns HTTP 429 Too Many Requests.
* Any limits hit will log "RATE LIMIT HIT!" in the logs at warning level and set up monitoring based on this. 
* Citizen OS FE generic error handler now handles 429 codes and specific or generic error messages can be shown:
    * Specific to login: "Sorry, too many login attempts have been made and login has been temporarily disabled. Please try again later, if problem persist, contact customer support."
    * Generic message whenever an API hits a rate limit: "Sorry, you have reached fair use limit of one or more API's. Please try again later or contact customer support."

**Comment by tiblu** [comment]
@EgidioRomano Released the input rate limit solution. I think it's good enough. Also have an onging discussion with Heroku on the real IP issues. Have kept this issue posted on the discussion.

The drawback of this solution is deliberately locking user accounts, but that we can detect from monitoring.

**Comment by tiblu** [comment]
Heroku:
```
Hi there,

Apologies for not making this clear enough. Your proposals have not gone under the radar, I was suggesting that relying on X-Forwarded-For is considered not secure for the reasons I mentioned.

Can you please elaborate what kind of proxies are you talking about? What would the example request lifecycle? I seem to lack some knowledge here.

Proxies are not the same as spoofed x-forwarded-for. If a client connecting to a web server through an HTTP proxy or a load balancer. The proxies would be on the right of the connecting client IP. Spoofed IPs would be considered the connecting client IP in this case.

How it works now: it does NEW X-Forwared-For = X-Forwarded-For + connecting client IP. Thats a fact, that I have proven above.

That is correct but as mentioned in the link you've mentioned:

the right-most IP address is the IP address of the most recent proxy and the left-most IP address is the IP address of the originating client.

Heroku follows this practice.
This means that if the proxy IP that the client is behind is 4.4.4.4 you'd see:

app[web.1]: "x-forwarded-for": "8.8.8.8, 82.131.73.205, 4.4.4.4"
So the result is "x-forwarded-for": "spoofed x-forwarded-for, 82.131.73.205, proxies". This means that it's impossible to know which one is the connecting client IP. Since you can not assume the amount of the proxies or spoofed X-Forwarded-For

Hope this helps. Please let me know if you need further clarification on this.

Regards,
Aly
````

**Comment by tiblu** [comment]
@tiblu:

Hi!

Thanks for the clarification, I think I got it now and you seem to be right on this one.

Getting a spoof-proof/more reliable client IP. I understand that with proxy chains it may become tricky, like we have CloudFlare proxy.

I have a few questions/options that I would like you to validate:

* Can I somehow make it impossible to access our Heroku app over Heroku DNS directly (that is not on *.herokuapp.com), only through CloudFlare proxies. Then we can trust the `cf-connecting-ip` set by CloudFlare?
* Would it make sense for Heroku to implement GW functionality where the actual connecting IP is put in a separate request header like `X-Real-IP` (Used by Oracle, Nginx real ip module...).? CloudFlare has it as `cf-connecting-ip`. The logic is that every maintainer must know if they have a proxy in front of Heroku or not, thus know if they can trust the IP. For those who don't have proxy in front, the actual connecting client IP would be correct. 
* Would it make sense for system owner to be able to configure Heroku GW behavior on the `X-Forwarded-For` header - GW to trust or not trust the incoming `X-Forwarded-For` header? If "no trust" is specified, GW will OVERWRITE the `X-Forwarded-For`, IF "trust", GW will add to the `X-Forwarded-For` like it does now. 

Also, understand that IP based restrictions are slippery slope, but security as I see it, is applying many layers  top of each other. IP based restrictions make attacks more expensive but not impossible. 

Thanks again for the help!

Regards,
Mikk
