### ISSUE TITLE
Activity feed - add argument moderation activity

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#24]
**Overview**

When a Moderator moderates an argument, there is no info about it in the activity feed.

**TODO**

- [ ] Record moderation activity 
- [ ] Verify that the activity is shown in the `*/activities` outputs.
- [ ] Verify that it's shown properly in the FE (https://github.com/citizenos/citizenos-fe). Make tasks needed for localisation.
