### ISSUE TITLE
BUG: API - replying to deleted (hidden) argument throws 500 Internal Server Error

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#27]
**Reproduce**

* Create a new argument
* Delete the argument
* Reply to the argument

**Result**

* 500 Server Error on posting the reply

**Expected**

**TODO**

- [x] Disable "Reply/Report/Up-Downvote" buttons for hidden arguments
- [x] Add a "disable reason" message IF possible
- [x] Citizen OS API to return sensible HTTP code and not throw 500

**Comment by tiblu** [comment]
@loorm @ilmartyrk What should happen from User experience perspective if a User replies to a deleted (hidden) argument? Think from FE perspective and we'll do the API behavior based on that.

Questions in my head:
* FE: Should the "Reply" button even exist in the UI?
* API: What would API do, if someone calls the deletion from API and the argument has been already deleted?

**Comment by tiblu** [comment]
> @loorm @ilmartyrk What should happen from User experience perspective if a User replies to a deleted (hidden) argument? Think from FE perspective and we'll do the API behavior based on that.
> 
> Questions in my head:
> 
> * FE: Should the "Reply" button even exist in the UI?
> * API: What would API do, if someone calls the deletion from API and the argument has been already deleted?

Implementation details in the first comment.

**Comment by ilmartyrk** [comment]
@tiblu is 404 sensible or would 403 make more sense? I'll have to add that current 500 error was thrown while adding activity as parent object was empty thus not having the `toJSON()` method, actual reply was posted and is visible after page reload.

**Comment by tiblu** [comment]
In my head 404 makes more sense, as it is "deleted" thus "does not exist".

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/c440a32525b9102c0e807859f70f5be1c3b89857 and https://github.com/citizenos/citizenos-api/commit/902d2b9e534fc300f0075fa3785fdaa839a7422d
