### ISSUE TITLE
CLEANUP: Remove API routes that are not used

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#31]
**TODO**

**NOTE:** Verify usage against application logs!

- [ ] REMOVE API: ``GET /api/users/:userId/groups/:groupId/topics``, which is replaced by ``GET /api/users/:userId/groups/:groupId/members/topics``
- [ ] REMOVE API ROUTE: ``GET/POST /api/users/:userId/groups/:groupId/members`` which is replaced by ``/api/users/:userId/groups/:groupId/members/users``
- [ ] REMOVE API ROUTE: ``PUT/DELETE /api/users/:userId/groups/:groupId/members/:userId`` which is replaced by ``/api/users/:userId/groups/:groupId/members/users/:userId``

**Comment by anettlinno** [comment]
Triage 37. Check API code and harvest out those end points and parts of code that we don´t use any more. Approx. dev. time 1h. Sending to development.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk will assume OK to go to 'later' as old, dormant issue
