### ISSUE TITLE
API: `PUT /topics/:topicId/members/users` and `PUT /groups/:groupId/members/users` to return HTTP 422 if any of the `userId`-s is not a valid email or UUID. 

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#39]
**Overview**

Initial implementation of  `PUT /topics/:topicId/members/users` and `PUT /groups/:groupId/members/users` just ignore invalid UUID-s and e-mails.  The shortcoming of this is that if you insert invalid e-mail/UUID, you will never know if the invites actually succeeded. 
To provide adequate feedback, he input data should be validated and an error code returned.

**TODO**

- [ ] `PUT /topics/:topicId/members/users`  to return HTTP 422 IF any of the `userId` is invalid e-mail or UUID
- [ ] `PUT /groups/:groupId/members/users`  to return HTTP 422 IF any of the `userId` is invalid e-mail or UUID
- [ ] Update tests accordingly
- [ ] Once done, create a task OR implement a fix in the Citizen OS FE (https://github.com/citizenos/citizenos-fe) project to update our UI to show the error.

**Comment by anettlinno** [comment]
Triage 37. Still relevant but low priority. Approx. dev. time 6 hours. Sending it to To do.
