### ISSUE TITLE
E-mails - localisation with Crowdin

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#41]
**Related to:**

* https://github.com/citizenos/citizenos-api/issues/6

**TODO**

- [x] Move templates to Citizen OS API Crowdin project - https://crowdin.com/project/citizen-os-api
- [x] While on it, also translate Etherpad templates
- [x] Make sure `governmentNotification.mu` is NOT translated and is in ET by default.
- [x] E-mail testing - think how the testing should be performed? Implement. Right after running all tests I just `grep "e-mail" | grep -c "ERROR"` and expect 0 which means e-mail sending code worked, but I dont check the payloads that were sent. The possible problems that this kind of testing does not catch are wrong language, wrong partner, wrong template, wrong receiver, wrong subject etc.

**Comment by tiblu** [comment]
The testing part - sending out emails synchronously. If the e-mail fails, automated tests start to fail as the API requests will fail.
