### ISSUE TITLE
Report a Topic

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#5]
There is a way to report an argument (comment) but not a whole Topic.

**TODO**

- [x] API - create report `POST /api/topics/:topicId/reports`.
- [x] API - create report `POST /api/topics/:topicId/reports` to return moderation URL instantly when reported by a moderator, this will enable instant moderation without sending an e-mail.
- [x] Emails - move to Crowdin (https://github.com/citizenos/citizenos-api/issues/41)
- [x] API - unify restricted token generation and validation (https://github.com/citizenos/citizenos-api/issues/70)
- [x] API - read a report `GET /api/topics/:topicId/reports/:reportId`
- [x] API - moderate a report `POST /api/topics/:topicId/reports/:reportId/moderate`.
- [x] API - review
- [x] FE: Report a topic menu item
- [x] FE: Report a topic form
- [x] FE: Report moderation menu item - **DONE: ** Not separate menu item but part of the red notification on the top.
- [x] FE: Report moderation form
- [x] FE: Moderated topic visuals - warning overlay etc. - https://projects.invisionapp.com/d/main#/console/9829159/333531893/preview https://projects.invisionapp.com/d/main#/console/9829159/333531894/preview
- [x] FE: No search engine indexing for reported content! - in the initial scope, only `GET /topcs/;topicId`, other views need to be addressed separately - https://github.com/citizenos/citizenos-api/issues/5#issuecomment-496509538
- [x] FE disable/hide upvote/downvote when not logged in
- [x] FE: Missing report topic icon on the top right of the topic!
- [x] FE: Disable action buttons when request is in progress!
- [x] Emails:  As described in https://app.citizenos.com/en/topics/ac8b66a4-ca56-4d02-8406-5e19da73d7ce
- [x] E-mails: `linkedData` usage is funky.
- [x] E-mails: Get rid of `social: config.email.social` option?
- [x] E-mails: Application links in the emails are same for all languages, we may want to support links per language? **DONE:** Overthinking this? FE can will do the language resolution.
- [x] E-mails: Moderation guidelines links! - **DONE:** Can be changed with `config.email.linkViewModerationGuidelines`. Defaults to https://app.citizenos.com/en/topics/ac8b66a4-ca56-4d02-8406-5e19da73d7ce
- [x] E-mails: Date formatting! **DONE:** - `LLL Z`
- [x] E-mails - TESTING: REVIEW SEND TO PARLIAMENT E-MAILS!
- [x] CHANGELOG.md
- [x] DB migrations!

![image](https://user-images.githubusercontent.com/7405383/48413182-9dc27680-e74f-11e8-8b35-7734e90e2561.png)

**Comment by rupeshparab** [comment]
@tiblu 
I am interested in taking this up, by when do you need this to be completed?
Do you want something like this, when reporting a topic?

![image](https://user-images.githubusercontent.com/6897505/41282629-3136d5a4-6e52-11e8-810e-694c79fa427e.png)

**Comment by tiblu** [comment]
Hi!

Thanks for the interest in contributing to CitizenOS.

We don't have a very specific time frame for this feature, but to comply
with legal requirements it is a must have.

So whenever you have time, you're very welcome to contribute. If you have
any further questions, please let me know.

**Comment by tiblu** [comment]
@loorm What do you think we should do when a Topic gets moderated?

I think we should follow our rule of hiding not deleting. 
We should also consider a situation when the Topic gets fixed, then we could make it visible again.

**Comment by tiblu** [comment]
I am to create some new e-mail templates so I created a side track - https://github.com/citizenos/citizenos-api/issues/41 and will fix this before I complete this task.

**Comment by tiblu** [comment]
Marked as "blocked", we need to discuss what the UX will be.
All the work done so far is in the "report_topic" branch - https://github.com/citizenos/citizenos-api/tree/report_topic

**Comment by loorm** [comment]
My 10 cents:
- both public and private topics can be reported, regardless of their status (even closed topics, because they are still visible)
- reporting should be similar to argument reporting (same reasons, same dialog asking for explanation)
- any logged in user should be able to report any public topic (need to check legals, if non-logged in users also need to be able to report)
- if a public topic is reported, it is automatically switched to private, pending fixing or moderator decision, if topic is in voting, voting should be halted - THIS IS AN IDEA TO BE DISCUSSED
- moderation cycle should be started similar to argument reporting incl. topic owner notification etc.
- there should be a clear notification / overlay to indicate, that the topic contains potentially offensive material, that has been reported, the decision is pending and user should read on at their own risk
- if a topic is found to be offensive and author does not fix, we don't show it on front page, but possibly will show it to subscribed users, only with an overlay similar to "deleted" arguments.

**Comment by tiblu** [comment]
**Agreements**

* Report public & private Topics
* ANY user can report (**TODO:** confirm with Kati)
* Report notifications
    * Private topics - creator, sent to `admin` level members
    * Public topics - creator, moderators, `admin` level members
* What happens to reported Topic?
    * Nothing happens on report itself BEFORE moderated
    * When moderated:
         * Overlay the Topic in READ ONLY
         * Notification bar in EDIT MODE ("Youre editing moderated topics")
* Report reason "Contains spam or is unrelated to topic" REMOVED for Topics
    * Split into 2 "Contains spam" / "Unrelated to Topic"

**Comment by kevincrepin** [comment]
Couple more questions from my end:

- Do we show who reported the topic publicly?

- When reporting, is the additional text field obligatory? Do we show that input publicly?

Overlay: https://projects.invisionapp.com/d/main#/console/9829159/333531893/preview
Notification: https://projects.invisionapp.com/d/main#/console/9829159/333531894/preview
Edit mode: https://projects.invisionapp.com/d/main#/console/9829159/333531895/preview

@tiblu let's discuss when you're back from vacation.

**Comment by tiblu** [comment]
**Overview**

We issue restricted use tokens for very specific authorization:
* For example we issue a token to topic Moderators, to moderate a Topic. This token is sent in e-mail.
* We issue a token to Riigikogu (Parliament) so that they can download signed Topic container.
* We issue a token to User after singing a Vote so that signed container can be downloaded. Not all Users have to be logged in for signing thus enables unauthenticated download of their Vote.
...

**Problem**

The restricted use token format varies quite a bit in the system and creates significant amount of complexity/confusion/overhead in the code-base. It calls for a rewrite so that we can reuse the issuing and validation code.

**What token formats are present, where are they issued?**

**Comment by tiblu** [comment]
The current solution to be implemented:

* Report a topic
* Send e-mail to moderators/admin members
* WHEN moderated, set the Topic to private AND send e-mail to admin members.
* Moderator DOES NOT EDIT the Topic itself.
* UI overlays and notifications for reported Topics.

Out of scope:

* "Submit for review" - the admin members take responsibility of editing the Topic and making it "public" again. If they did not resolve it properly, the Topic will be reported again...

**Comment by tiblu** [comment]
@loorm

**Comment by tiblu** [comment]
### E-mails

What emails to send out and when?

#### On reporting a Topic - `POST /api/users/:userId/topics/:topicId/reports`
That is on the event of User reporting a Topic.

#### On Topic moderation - `POST /api/topics/:topicId/reports/:reportId/moderate`
That is when Moderator takes action and thus applies restrictions to a Topic.

#### On submitting Topic for a review - `POST /api/topics/:topicId/reports/review`
That is when a User requests a review on a Topic to lift the restrictions set by a Moderator from the Topic.

#### On Topic report resolution - `POST /api/topics/:topicId/reports/resolve`
When a Moderator marks all violations as resolved and removes all restrictions applied to the Topic.

**Comment by tiblu** [comment]
@kevincrepin We've added the topic moderation e-mail content to the Citizen OS public topic. We need your magic touch to make those e-mails shine! https://app.citizenos.com/en/topics/ac8b66a4-ca56-4d02-8406-5e19da73d7ce?argumentsPage=1

**Comment by tiblu** [comment]
E-mail designs are done, ready to continue with the dev!

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/56886914-c8438a00-6a78-11e9-886a-a5fc2cf5ff24.png)

Source: https://projects.invisionapp.com/d/main#/console/9829159/333531893/preview

**Comment by tiblu** [comment]
@kevincrepin We had a discussion about moderation with @loorm.

The outcomes are:

* There can only be one report active at a time. Why? To avoid overwhelming moderators with reports.
* Once Topic is reported, reporting functionality is hidden/disabled. 
* Once Topic is reported, NOT moderated, there has to be a notification "already reported" somewhere.
* Three can only be one review request at a time. Why? To avoid overwhelming moderators with review  requests.
* Once Topic is sent for a review, "send for a review" functionality is hidden/disabled.
* Once Topic is sent for a review, there has to be  a notification "already sent for a review" somewhere.
* Moderators should be able to lift restrictions from a Topic WITH AND WITHOUT a review request.


@kevincrepin Things we need to update/create:

* The moderated Topic overlay ("This topic has been reported") - https://projects.invisionapp.com/d/main#/console/9829159/333531893/preview
    * There can only be 1 report, 1 reason, 1 explanation text.
    * We need to reflect the current status on that overlay so that User has clear idea in what phase the moderation process is:
        * Waiting for update & review request - Topic has been moderated, now any of the Members with "edit" permissions needs to update the content and send a review request.
        * Pending moderator review - Topic has been sent for a review to Moderators
* We need a place where Moderators can do their work:
    * Approve or reject a report, 
    * Approve or reject review request. 
    * Moderators should be able to lift restrictions without a review request.
    * We need to implement it so that we make an effort in making sure Moderator actually read the Topic.

**Comment by kevincrepin** [comment]
I think for the current version of the platform we could reuse the "my Topics" layout: https://projects.invisionapp.com/d/main#/console/9829159/361400700/preview

So we have the reported topics on the left side, they're also "filterable" in case of many. On the right side we have the same general information on the topic, but in the second block we have the report information and actions.
In the menu there would be an additional menu item to get to the reported topics, but only for moderators.

Alternatively we could also just have this information as part of the "My Topics", but it will not be so visible then. Even through notifications it might still be a bit hard to find the reported topics then...

Dialog window update: https://projects.invisionapp.com/d/main#/console/9829159/333531893/preview

**Comment by tiblu** [comment]
@kevincrepin We discussed the layout with @loorm and it looks good to us.

* We're missing is a "all reports" view which is shown when there is nothing reported.
* Should we have shortcut link in the Topic view "Options" menu to take to the "reported view" for moderation? Something that pops in your eye.

**Comment by tiblu** [comment]
@kevincrepin What do you suggest we do with:
* Home page - if there is a reported topic, how do we mark it? One thing for sure - content should not be visible to users.
* Search results - if there is a reported topic, we cannot show the content title in the search results in case the violation is in the title. So we could either mark it somehow and hide content or not show the result at all.

![image](https://user-images.githubusercontent.com/7405383/58480400-f47b2500-8162-11e9-91fd-ce779f1c46b6.png)

![image](https://user-images.githubusercontent.com/7405383/58480449-0ceb3f80-8163-11e9-83d9-4753c2a79ff4.png)

**Comment by tiblu** [comment]
@loorm 

Notes on the Topic report implementation v1:

* In this scope, we have resolved the Topic view (`/topics/:topicId`), but in the future we MUST tackle other views that expose Topic content. See https://github.com/citizenos/citizenos-api/issues/5#issuecomment-496509538
* Currently we create no activities to the activity feed about the reporting. We need to agree what activites we want to create.
* The community guideline links in the emails and the FE take to Citizen OS Topic Moderation Topic. We need to polish it's content. https://app.citizenos.com/en/topics/ac8b66a4-ca56-4d02-8406-5e19da73d7ce
* Currently we hide "Report" actions when Topic has already been reported and is waiting for Moderator action. Maybe we want some other UX, to let Users know that it's pending Moderator review?
* While you can have one report request at the time, we allow multiple "Review" requests, each sends Moderators a new e-mail. We MAY want to reconsider it - make 1 review request be open at the time, but then that means we have to have a means keeping track and closing review requests. Right now review request only sends e-mails, it has no state stored in DB.

**Comment by tiblu** [comment]
Citizen OS deployment notes:

* DB backup before update - b1242

**Comment by oksks** [comment]
Just arrived here, as I went through the Report Topic flow (for Crowdin screenshots) and it's really weird to go through a proper flow, click the "YES I'M ABSOLUTELY SURE" (or something) in the "Are you sure you want to report this topic?" window, and then have everything disappear without any confirmation that I've actually gone through it successfully. 

Pretty please add a confirmation - maybe even pin a red notification to the topic's heading, that "You've reported this topic on DD.MM.YYYY".

**Comment by KatiVellak** [comment]
Legally reviewed, during the discussions legal input provided.
